# Generated by Django 2.2.6 on 2019-11-02 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20191101_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article2tag',
            name='tag',
            field=models.ForeignKey(help_text='标签', on_delete=django.db.models.deletion.CASCADE, related_name='Article2Tag_tag', to='articles.Tag', verbose_name='标签'),
        ),
        migrations.CreateModel(
            name='WebCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='网站分类名称', max_length=32, verbose_name='网站分类名称')),
                ('parent_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.WebCategory')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
