# Generated by Django 2.2.6 on 2019-11-02 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20191102_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='web_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_web_category', to='articles.WebCategory'),
        ),
    ]
