# Generated by Django 2.2.6 on 2019-11-02 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_web_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_set', to='articles.WebCategory'),
        ),
    ]
