# Generated by Django 2.2.6 on 2019-11-02 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20191102_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_list', to='articles.WebCategory'),
        ),
    ]
