# Generated by Django 2.2.6 on 2019-10-24 11:14

import Blog.apps.authentication.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20191024_0953'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', Blog.apps.authentication.models.UserManager()),
            ],
        ),
    ]
